# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.7

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/lychee/Documents/CITS3402/PercolationProblems

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/lychee/Documents/CITS3402/PercolationProblems

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/lychee/Documents/CITS3402/PercolationProblems/CMakeFiles /home/lychee/Documents/CITS3402/PercolationProblems/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/lychee/Documents/CITS3402/PercolationProblems/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named PercolationProblems

# Build rule for target.
PercolationProblems: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 PercolationProblems
.PHONY : PercolationProblems

# fast build rule for target.
PercolationProblems/fast:
	$(MAKE) -f CMakeFiles/PercolationProblems.dir/build.make CMakeFiles/PercolationProblems.dir/build
.PHONY : PercolationProblems/fast

NodeBond.o: NodeBond.cpp.o

.PHONY : NodeBond.o

# target to build an object file
NodeBond.cpp.o:
	$(MAKE) -f CMakeFiles/PercolationProblems.dir/build.make CMakeFiles/PercolationProblems.dir/NodeBond.cpp.o
.PHONY : NodeBond.cpp.o

NodeBond.i: NodeBond.cpp.i

.PHONY : NodeBond.i

# target to preprocess a source file
NodeBond.cpp.i:
	$(MAKE) -f CMakeFiles/PercolationProblems.dir/build.make CMakeFiles/PercolationProblems.dir/NodeBond.cpp.i
.PHONY : NodeBond.cpp.i

NodeBond.s: NodeBond.cpp.s

.PHONY : NodeBond.s

# target to generate assembly for a file
NodeBond.cpp.s:
	$(MAKE) -f CMakeFiles/PercolationProblems.dir/build.make CMakeFiles/PercolationProblems.dir/NodeBond.cpp.s
.PHONY : NodeBond.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/PercolationProblems.dir/build.make CMakeFiles/PercolationProblems.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/PercolationProblems.dir/build.make CMakeFiles/PercolationProblems.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/PercolationProblems.dir/build.make CMakeFiles/PercolationProblems.dir/main.cpp.s
.PHONY : main.cpp.s

percolation.o: percolation.cpp.o

.PHONY : percolation.o

# target to build an object file
percolation.cpp.o:
	$(MAKE) -f CMakeFiles/PercolationProblems.dir/build.make CMakeFiles/PercolationProblems.dir/percolation.cpp.o
.PHONY : percolation.cpp.o

percolation.i: percolation.cpp.i

.PHONY : percolation.i

# target to preprocess a source file
percolation.cpp.i:
	$(MAKE) -f CMakeFiles/PercolationProblems.dir/build.make CMakeFiles/PercolationProblems.dir/percolation.cpp.i
.PHONY : percolation.cpp.i

percolation.s: percolation.cpp.s

.PHONY : percolation.s

# target to generate assembly for a file
percolation.cpp.s:
	$(MAKE) -f CMakeFiles/PercolationProblems.dir/build.make CMakeFiles/PercolationProblems.dir/percolation.cpp.s
.PHONY : percolation.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... PercolationProblems"
	@echo "... NodeBond.o"
	@echo "... NodeBond.i"
	@echo "... NodeBond.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... percolation.o"
	@echo "... percolation.i"
	@echo "... percolation.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

